services:
  - type: web
    name: india-oasis
    buildCommand: echo "No build step required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
